amazon-warehouse:
  - id: B087VM5XC6
    title: Xbox Series S
    price: 220
  - id: B08WJSJT4J
    title: Xbox Wireless Headset
    price: 75
  - id: B081FWVSG8
    title: Apple Lightning auf USB Kabel
    price: 12